<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
    <RootNamespace>Tally.Integration.Sample</RootNamespace>
    <AssemblyName>Tally.Integration.Sample</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Tally.Integration.SDK" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Mappings\Sales.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
